proiektua2/proiektua2/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using proiektua2;
using proiektua2.Models;
using proiektua2.Services;

namespace proiektua2.Controllers
{
    public class ProductosController : Controller
    {
        private readonly AdminDbContext _context;
        private readonly IProductoService _productoService;
        public ProductosController(AdminDbContext context, IProductoService productoService)
        {
            _productoService = productoService;
            _context = context;
        }

        // GET: Productos
        public async Task<IActionResult> Index()
        {
            var adminDbContext = _context.Productos.Include(p => p.Categoria).Include(p => p.Marca);
            return View(await adminDbContext.ToListAsync());
        }
        public async Task<IActionResult> prueba()
        {
            
            return View();
        }
        public async Task<IActionResult> produktoKategoria()
        {

            return View(_productoService.GustiakEskaintzak());
        }
        public async Task<IActionResult> produktoMarka()
        {

            return View(_productoService.GustiakEskaintzak());
        }

        // GET: Productos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .Include(p => p.Categoria)
                .Include(p => p.Marca)
                .FirstOrDefaultAsync(m => m.id == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // GET: Productos/Create
        public IActionResult Create()
        {
            ViewData["Categoriaid"] = new SelectList(_context.Categoria, "id", "id");
            ViewData["Marcaid"] = new SelectList(_context.Marcas, "id", "id");
            return View();
        }

        // POST: Productos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("idProductos,Marcaid,Categoriaid,descripcion,precio,precioTotal,imagen,Eskaintza,Deskontua")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(producto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Categoriaid"] = new SelectList(_context.Categoria, "id", "id", producto.Categoriaid);
            ViewData["Marcaid"] = new SelectList(_context.Marcas, "id", "id", producto.Marcaid);
            return View(producto);
        }

        // GET: Productos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }
            ViewData["Categoriaid"] = new SelectList(_context.Categoria, "id", "id", producto.Categoriaid);
            ViewData["Marcaid"] = new SelectList(_context.Marcas, "id", "id", producto.Marcaid);
            return View(producto);
        }

        // POST: Productos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("idProductos,Marcaid,Categoriaid,descripcion,precio,precioTotal,imagen,Eskaintza,Deskontua")] Producto producto)
        {
            if (id != producto.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(producto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductoExists(producto.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Categoriaid"] = new SelectList(_context.Categoria, "id", "id", producto.Categoriaid);
            ViewData["Marcaid"] = new SelectList(_context.Marcas, "id", "id", producto.Marcaid);
            return View(producto);
        }

        // GET: Productos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .Include(p => p.Categoria)
                .Include(p => p.Marca)
                .FirstOrDefaultAsync(m => m.id == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // POST: Productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var producto = await _context.Productos.FindAsync(id);
            _context.Productos.Remove(producto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductoExists(int id)
        {
            return _context.Productos.Any(e => e.id == id);
        }

        public Marca getIdmarca(int id)
        {


            var marca = _context.Marcas
                .FirstOrDefaultAsync(m => m.id == id);


            return marca.Result;
        }
        public Categoria getIdcategoria(int id)
        {


            var marca = _context.Categoria
                .FirstOrDefaultAsync(m => m.id == id);


            return marca.Result;
        }
        public async Task<IActionResult> categoriaProductuak(int id)
        {
            ViewBag.id = id;
            var adminDbContext = _context.Productos.Include(p => p.Categoria).Include(p => p.Marca);
            return View(await adminDbContext.ToListAsync());
        }
        public async Task<IActionResult> MarcaProductuak(int id)
        {
            ViewBag.id = id;
            var adminDbContext = _context.Productos.Include(p => p.Categoria).Include(p => p.Marca);
            return View(await adminDbContext.ToListAsync());
        }
        public async Task<IActionResult> detatellak2(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            /* var pro = await _context.Productos
                 //.Include(a => a.Marca)

                 .FirstOrDefaultAsync(m => m.idProductos == id);*/
            var Contextproductos = (from Productos in _context.Productos
                                    join Marcas in _context.Marcas
                                    on Productos.Marcaid equals Marcas.id
                                    join Categoria in _context.Categoria
                                    on Productos.Categoriaid equals Categoria.id
                                    select new Producto
                                    {
                                        id = Productos.id,
                                        Marcaid = Productos.Marcaid,
                                        Marca = new Marca(Productos.Marcaid, Marcas.Nombre),
                                        Categoriaid = Productos.Categoriaid,
                                        Categoria = new Categoria(Productos.Categoriaid, Categoria.Nombre),
                                        descripcion = Productos.descripcion,
                                        precio = Productos.precio,
                                        precioTotal = Productos.precioTotal,
                                        imagen = Productos.imagen,
                                        Eskaintza = Productos.Eskaintza,
                                        Deskontua = Productos.Deskontua,

                                    }).FirstOrDefaultAsync(m => m.id == id);

            Producto pro = new Producto(Contextproductos.Result.id, Contextproductos.Result.Marcaid, Contextproductos.Result.Marca, Contextproductos.Result.Categoriaid, Contextproductos.Result.Categoria, Contextproductos.Result.descripcion, Contextproductos.Result.precio, Contextproductos.Result.precioTotal, Contextproductos.Result.imagen, Contextproductos.Result.Eskaintza, Contextproductos.Result.Deskontua);

            return View(await Contextproductos);
            /*if (pro == null)
            {
                return NotFound();
            }

            return View(pro);*/
        }
    }
}

proiektua2/proiektua2/Controllers/SaskiasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using proiektua2;
using proiektua2.Models;
using proiektua2.Services;
using proiektua2.ViewModels;

namespace proiektua2.Controllers
{
    public class SaskiaController : Controller
    {
        private readonly AdminDbContext _context;
        private readonly ISaskiaService _saskiaService;
        private readonly IProductoService _ardoaService;
        public static Guid tempCartId ;
        public SaskiaController(AdminDbContext context,ISaskiaService saskiaService, IProductoService ardoaService)
        {
            _saskiaService = saskiaService;
            _ardoaService = ardoaService;
            _context = context;
        }

       /* public SaskiaController(AdminDbContext context)
        {
            _context = context;
        }*/

        // GET: Saskias
        public async Task<IActionResult> Index()
        {
            var cart = Saskia.SaskiaLortu();
            var saskiaViewModel = new SaskiaViewModel(); //ViewModel bat erabiliko dugu
            saskiaViewModel.SaskiaAleak = _saskiaService.SaskiaLortuAleak(cart.SaskiaId);
            saskiaViewModel.SaskiaGuztira = _saskiaService.Guztira(cart.SaskiaId);

            return View(saskiaViewModel);


            
        }
      
        public IActionResult SaskiaGehitu(int id)
        {
            var cart = Saskia.SaskiaLortu(); //aurretik sortu dugun Saskia klasea erabiliz
            _saskiaService.SaskiaGehitu(id, cart.SaskiaId); //zerbitzu berrian karritoan gehitzeko
            return RedirectToAction("Index");
        }
        public IActionResult SaskiaGehituJson(int id)
        {
            var cart = Saskia.SaskiaLortu();

            var saskiaItem = _saskiaService.SaskiaAleaDatuak(id, cart.SaskiaId);

            _saskiaService.SaskiaGehitu(id, cart.SaskiaId);

            var results = new SaskiaKenduViewModel
            {
                Mezua = HtmlEncoder.Default.Encode(saskiaItem.Producto.Nombre) + " zure saskira gehitu da",
                SaskiaGuztira = _saskiaService.Guztira(cart.SaskiaId),
                //ItemGuztiak = _saskiaService.ItemGuztiak(cart.SaskiaId),
                ItemKopurua = saskiaItem.Kantitatea,
                EzabatutakoId = id
            };

            return Json(results);
        }
        [HttpPost]
        public ActionResult SaskiaKendu(int id)
        {
            var cart = Saskia.SaskiaLortu();

            var saskiaItem = _saskiaService.SaskiaAleaDatuak(id, cart.SaskiaId);

            int itemCount = _saskiaService.SaskiaKendu(id, cart.SaskiaId);

            var results = new SaskiaKenduViewModel
            {
                Mezua = HtmlEncoder.Default.Encode(saskiaItem.Producto.Nombre) + " zure saskitik kendu da",
                SaskiaGuztira = _saskiaService.Guztira(cart.SaskiaId),
                ///ItemGuztiak = _saskiaService.ItemGuztiak(cart.SaskiaId),
                ItemKopurua = itemCount,
                EzabatutakoId = id
            };

            return Json(results);
        }

        // GET: Saskias/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var saskia = await _context.Saskia
                .FirstOrDefaultAsync(m => m.SaskiaId == id);
            if (saskia == null)
            {
                return NotFound();
            }

            return View(saskia);
        }

        // GET: Saskias/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Saskias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SaskiaId")] Saskia saskia)
        {
            if (ModelState.IsValid)
            {
                _context.Add(saskia);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(saskia);
        }

        // GET: Saskias/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var saskia = await _context.Saskia.FindAsync(id);
            if (saskia == null)
            {
                return NotFound();
            }
            return View(saskia);
        }

        // POST: Saskias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("SaskiaId")] Saskia saskia)
        {
            if (id != saskia.SaskiaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(saskia);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SaskiaExists(saskia.SaskiaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(saskia);
        }

        // GET: Saskias/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var saskia = await _context.Saskia
                .FirstOrDefaultAsync(m => m.SaskiaId == id);
            if (saskia == null)
            {
                return NotFound();
            }

            return View(saskia);
        }

        // POST: Saskias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var saskia = await _context.Saskia.FindAsync(id);
            _context.Saskia.Remove(saskia);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


private bool SaskiaExists(string id)
        {
            return _context.Saskia.Any(e => e.SaskiaId == id);
        }
    }
}

proiektua2/proiektua2/Views/Productos/Create.cshtml
@model proiektua2.Models.Producto

@{
    ViewData["Title"] = "Create";
}
@{

    if (AdminDbContext.user.tipo == "admin")
    {
        <h1>Create</h1>

        <h4>Producto</h4>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Marcaid" class="control-label"></label>
                        <select asp-for="Marcaid" class="form-control" asp-items="ViewBag.Marcaid"></select>
                    </div>
                    <div class="form-group">
                        <label asp-for="Categoriaid" class="control-label"></label>
                        <select asp-for="Categoriaid" class="form-control" asp-items="ViewBag.Categoriaid"></select>
                    </div>
                    <div class="form-group">
                        <label asp-for="descripcion" class="control-label"></label>
                        <input asp-for="descripcion" class="form-control" />
                        <span asp-validation-for="descripcion" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="precio" class="control-label"></label>
                        <input asp-for="precio" class="form-control" />
                        <span asp-validation-for="precio" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="precioTotal" class="control-label"></label>
                        <input asp-for="precioTotal" class="form-control" />
                        <span asp-validation-for="precioTotal" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="imagen" class="control-label"></label>
                        <input asp-for="imagen" class="form-control" />
                        <span asp-validation-for="imagen" class="text-danger"></span>
                    </div>
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="Eskaintza" /> @Html.DisplayNameFor(model => model.Eskaintza)
                        </label>
                    </div>
                    <div class="form-group">
                        <label asp-for="Deskontua" class="control-label"></label>
                        <input asp-for="Deskontua" class="form-control" />
                        <span asp-validation-for="Deskontua" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Index">Back to List</a>
        </div>
        } }
        @section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        }
                    
                

proiektua2/proiektua2/Views/Productos/MarcaProductuak.cshtml
@model IEnumerable<proiektua2.Models.Producto>

@{
    ViewData["Title"] = "MarcaProductuak";
}

<h1>categoriaProductuak</h1>

<div id="carousel-example" class="carousel slide hidden-xs" data-ride="carousel">
    <div class="carousel-inner">
        @{var itemLerroko = 0;
            var fila1 = false;}

        @{
            foreach (var item in Model)
            {
                if (item.Marcaid == ViewBag.id)
                {
                    if (item.Eskaintza == true)
                    {
                        if (itemLerroko == 0)
                        {
                            if (fila1 == false)
                            {
                                @:<div class="carousel-item active">
                                    @:    <div class="row">
                                    }
                                    else
                                    {
                                        @:<div class="item">
                                            @:    <div class="row  ">
                                            }
                                        }


                                        <div class="col-sm">
                                            <div class="col-item border ">
                                                <div class="photo text-center">
                                                    <img class="img-responsive irudia" src="\images\productos\@item.imagen" width="150" height="130" />
                                                </div>
                                                <div class="info">
                                                    <div class="row">
                                                        <div class="price col-md-6">
                                                            <h5>
                                                                @item.descripcion
                                                            </h5>

                                                            <span class="tachado">@item.precio</span>
                                                            @item.Deskontua %
                                                            @{ float eskaintza = item.precio - (item.precio * item.Deskontua) / 100;}
                                                            <h5 class="price-text-color">
                                                                @eskaintza
                                                            </h5>
                                                        </div>
                                                        <div class="  d-md-block col-md-6">
                                                            <i class="price-text-color fa fa-star"></i><i class="price-text-color fa fa-star">
                                                            </i><i class="price-text-color fa fa-star"></i><i class="price-text-color fa fa-star">
                                                            </i><i class="fa fa-star"></i>
                                                        </div>
                                                    </div>
                                                    <div class=" clear-left">
                                                        <p class="btn-add">
                                                            <i class="fa fa-shopping-cart"></i><a asp-area="" asp-controller="Saskia" asp-action="SaskiaGehitu" asp-route-id="@item.id">Karritora gehitu</a>
                                                        </p>
                                                        <p class="btn-details">
                                                            <i class="fa fa-list"></i><a asp-area="" asp-controller="Productos" asp-action="detatellak2" asp-route-id="@item.id">Detaile gehiago</a>
                                                        </p>
                                                    </div>
                                                    <div class="clearfix">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        itemLerroko++;
                                        fila1 = true;
                                        if (itemLerroko >= 3)
                                        {
                                            @*  @:</div>*@
                                        @:</div>
                                        itemLerroko = 0;
                                    }
                                }
                            }
                        }
        }
    </div>
</div>
</div>
</div>
</div>

proiektua2/proiektua2/Views/Productos/categoriaProductuak.cshtml
@model IEnumerable<proiektua2.Models.Producto>

@{
    ViewData["Title"] = "categoriaProductuak";
}

<h1>categoriaProductuak</h1>

<div id="carousel-example" class="carousel slide hidden-xs" data-ride="carousel">
    <div class="carousel-inner">
        @{var itemLerroko = 0;
            var fila1 = false;}

        @{
            foreach (var item in Model)
            {
                if (item.Categoriaid== ViewBag.id)
                {
                    if (item.Eskaintza == true)
                    {
                        if (itemLerroko == 0)
                        {
                            if (fila1 == false)
                            {
                                @:<div class="carousel-item active">
                                    @:    <div class="row">
                                    }
                                    else
                                    {
                                        @:<div class="item">
                                            @:    <div class="row  ">
                                            }
                                        }


                                        <div class="col-sm">
                                            <div class="col-item border ">
                                                <div class="photo text-center">
                                                    <img class="img-responsive irudia" src="\images\productos\@item.imagen" width="150" height="130" />
                                                </div>
                                                <div class="info">
                                                    <div class="row">
                                                        <div class="price col-md-6">
                                                            <h5>
                                                                @item.descripcion
                                                            </h5>

                                                            <span class="tachado">@item.precio</span>
                                                            @item.Deskontua %
                                                            @{ float eskaintza = item.precio - (item.precio * item.Deskontua) / 100;}
                                                            <h5 class="price-text-color">
                                                                @eskaintza
                                                            </h5>
                                                        </div>
                                                        <div class=" d-sm-none d-md-block col-md-6">
                                                            <i class="price-text-color fa fa-star"></i><i class="price-text-color fa fa-star">
                                                            </i><i class="price-text-color fa fa-star"></i><i class="price-text-color fa fa-star">
                                                            </i><i class="fa fa-star"></i>
                                                        </div>
                                                    </div>
                                                    <div class=" clear-left">
                                                        <p class="btn-add">
                                                            <i class="fa fa-shopping-cart"></i><a asp-area="" asp-controller="Saskia" asp-action="SaskiaGehitu" asp-route-id="@item.id">Karritora gehitu</a>
                                                        </p>
                                                        <p class="btn-details">
                                                            <i class="fa fa-list"></i><a asp-area="" asp-controller="Productos" asp-action="detatellak2" asp-route-id="@item.id">Detaile gehiago</a>
                                                        </p>
                                                    </div>
                                                    <div class="clearfix">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        itemLerroko++;
                                        fila1 = true;
                                        if (itemLerroko >= 3)
                                        {
                                            @*  @:</div>*@
                                        @:</div>
                                        itemLerroko = 0;
                                    }
                                }
                            }
                        }
        }
    </div>
    </div>
    </div>
    </div>
</div>

proiektua2/proiektua2/Views/Productos/detatellak2.cshtml
@model proiektua2.Models.Producto

@{
    ViewData["Title"] = "detatellak2";
}
@using proiektua2.Controllers


<div>
    <h4>Producto</h4>
    <hr />
    <dl class="row">

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Marca.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Categoriaid)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Categoria.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.descripcion)
        </dd>
        @{


        }
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.precio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.precioTotal) descuento:@Html.DisplayFor(model => model.Deskontua) :precio sin descuento:@Html.DisplayFor(model => model.precio)
        </dd>

        <dt class="col-sm-2">

        </dt>
        <dd class="col-sm-10">
            <img class="img-responsive irudia" src="\images\productos\@Html.DisplayFor(model => model.imagen)" width="150" height="130" />

        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Deskontua)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Deskontua)%
        </dd>
        <i class="fa fa-shopping-cart"></i>
        <a asp-area="" asp-controller="Saskia" asp-action="SaskiaGehitu" asp-route-id="@Html.DisplayNameFor(model => model.id)">Karritora gehitu</a>
    </dl>
</div>
<div class="well">
    @await Html.PartialAsync("_Disqus", Model)
</div>
<script id="dsq-count-scr" src="//pcgora-com.disqus.com/count.js" async></script>