proiektua2/proiektua2/Models/Saskia.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using proiektua2.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace proiektua2.Models
{
    public class Saskia
    {
        public string SaskiaId { get; set; }
        public const string CartSessionKey = "cartId";

        public static Saskia SaskiaLortu()
        {
            var cart = new Saskia();
            cart.SaskiaId = cart.SaskiaLortuId();
            return cart;
        }
        public static Saskia SaskiaLortu(Controller controller)
        {
            return SaskiaLortu();
        }
        public string SaskiaLortuId(HttpContext contestua)
        {
            if (contestua.Session.GetString(CartSessionKey) == null)
            {
                if (!string.IsNullOrWhiteSpace(contestua.User.Identity.Name))
                {
                    contestua.Session.SetString(CartSessionKey, contestua.User.Identity.Name);
                }
                else
                {
                    Guid tempCartId = Guid.NewGuid();
                    contestua.Session.SetString(CartSessionKey, tempCartId.ToString());
                }
            }
            return contestua.Session.GetString(CartSessionKey);
        }
        ///nuevo metodo
        public string SaskiaLortuId()
        {
            string id;
            if(CartSessionKey == "cartId") { 
            if (AdminDbContext.sesion == true)
            {
                Guid tempCartId = Guid.NewGuid();
                id = tempCartId.ToString();

            }
            else
            {
                id = CartSessionKey;
            }
            }
            return SaskiaController.tempCartId.ToString();
        }
    }

}

proiektua2/proiektua2/ViewModels/SaskiaViewModel.cs
using proiektua2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace proiektua2.ViewModels
{
    public class SaskiaViewModel
    {
        public IList<SaskiaAlea> SaskiaAleak { get; set; }
        public decimal SaskiaGuztira { get; set; }
    }
}

proiektua2/proiektua2/Controllers/OrdainduController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using proiektua2.Models;
using proiektua2.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace proiektua2.Controllers
{
    public class OrdainduController : Controller
    {
        private readonly AdminDbContext _context;
        private readonly ISaskiaService _saskiaService;
        public OrdainduController(AdminDbContext context, ISaskiaService saskiaService)
        {
            _saskiaService = saskiaService;
            _context = context;
        }
        public IActionResult Index()
        {
            ///var bezeroa = _saskiaService.BezeroaDatuak(HttpContext.User.Identity.Name);
            var bezeroa = _saskiaService.BezeroaDatuak(AdminDbContext.user.idusuario);
            return View();
        }
        public async Task<IActionResult> pedidosUsuarios()
        {
            return View(await _context.Pedidos.ToListAsync());
        }
        /*  [HttpPost]
          [ValidateAntiForgeryToken]
          public IActionResult Index([Bind("Abizena,Helbidea,Herrialdea,Hiria,Izena,Postakodea,Telefonoa")] BezeroaEskaera bezeroaEskaera)
          {
              if (ModelState.IsValid)
              {
                 ////// Bezeroen datuak gorde
                  bezeroaEskaera.Erabiltzailea = HttpContext.User.Identity.Name;
                  bezeroaEskaera.Data = DateTime.Now;
                  _saskiaService.EskaeraBezeroaGehitu(bezeroaEskaera);

                  /////////Eskaera gorde
                  var cart = Saskia.SaskiaLortu();
                  _saskiaService.EskaeraSortu(bezeroaEskaera, cart.SaskiaId);
                  return RedirectToAction("Osatu");
              }
              return View(bezeroaEskaera);
          }*/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(BezeroaEskaera bezeroaEskaera)
        {
           
            if (ModelState.IsValid)
            {
               /* try
                {*/
                    bezeroaEskaera.Erabiltzaileaid = AdminDbContext.user.idusuario;
                    bezeroaEskaera.Data = DateTime.Now;
                    var cart = Saskia.SaskiaLortu();
               
                /*Bezeroa konprobatu*/
                if (_saskiaService.BezeroaKonprobatu(bezeroaEskaera.Erabiltzaileaid))
                    {
                        _saskiaService.BezeroaAldatu(bezeroaEskaera);
                    }
                    else
                    {
                        _saskiaService.EskaeraBezeroaGehitu(bezeroaEskaera);
                    }
                    _saskiaService.ErosketaGehitu(bezeroaEskaera, cart.SaskiaId);
                    _saskiaService.SaskiaEzabatu(cart.SaskiaId);

                    return RedirectToAction("Osatu", new { id = bezeroaEskaera.Id });
                /* }
                 catch (Exception ex)
                 {
                     ModelState.AddModelError("errorea", ex.Message);
                 }*/
            }
            return View(bezeroaEskaera);
        }
    
        public IActionResult Osatu(int id)
        {
            ViewData["bezeroaId"] = id;
            return View();
        }
    
    }
}

   

proiektua2/proiektua2/Controllers/SaskiasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using proiektua2;
using proiektua2.Models;
using proiektua2.Services;
using proiektua2.ViewModels;

namespace proiektua2.Controllers
{
    public class SaskiaController : Controller
    {
        private readonly AdminDbContext _context;
        private readonly ISaskiaService _saskiaService;
        private readonly IProductoService _ardoaService;
        public static Guid tempCartId ;
        public SaskiaController(AdminDbContext context,ISaskiaService saskiaService, IProductoService ardoaService)
        {
            _saskiaService = saskiaService;
            _ardoaService = ardoaService;
            _context = context;
        }

       /* public SaskiaController(AdminDbContext context)
        {
            _context = context;
        }*/

        // GET: Saskias
        public async Task<IActionResult> Index()
        {
            var cart = Saskia.SaskiaLortu();
            var saskiaViewModel = new SaskiaViewModel(); //ViewModel bat erabiliko dugu
            saskiaViewModel.SaskiaAleak = _saskiaService.SaskiaLortuAleak(cart.SaskiaId);
            saskiaViewModel.SaskiaGuztira = _saskiaService.Guztira(cart.SaskiaId);

            return View(saskiaViewModel);


            
        }
      
        public IActionResult SaskiaGehitu(int id)
        {
            var cart = Saskia.SaskiaLortu(); //aurretik sortu dugun Saskia klasea erabiliz
            _saskiaService.SaskiaGehitu(id, cart.SaskiaId); //zerbitzu berrian karritoan gehitzeko
            return RedirectToAction("Index");
        }
        public IActionResult SaskiaGehituJson(int id)
        {
            var cart = Saskia.SaskiaLortu();

            var saskiaItem = _saskiaService.SaskiaAleaDatuak(id, cart.SaskiaId);

            _saskiaService.SaskiaGehitu(id, cart.SaskiaId);

            var results = new SaskiaKenduViewModel
            {
                Mezua = HtmlEncoder.Default.Encode(saskiaItem.Producto.Nombre) + " zure saskira gehitu da",
                SaskiaGuztira = _saskiaService.Guztira(cart.SaskiaId),
                //ItemGuztiak = _saskiaService.ItemGuztiak(cart.SaskiaId),
                ItemKopurua = saskiaItem.Kantitatea,
                EzabatutakoId = id
            };

            return Json(results);
        }
        [HttpPost]
        public ActionResult SaskiaKendu(int id)
        {
            var cart = Saskia.SaskiaLortu();

            var saskiaItem = _saskiaService.SaskiaAleaDatuak(id, cart.SaskiaId);

            int itemCount = _saskiaService.SaskiaKendu(id, cart.SaskiaId);

            var results = new SaskiaKenduViewModel
            {
                Mezua = HtmlEncoder.Default.Encode(saskiaItem.Producto.Nombre) + " zure saskitik kendu da",
                SaskiaGuztira = _saskiaService.Guztira(cart.SaskiaId),
                ///ItemGuztiak = _saskiaService.ItemGuztiak(cart.SaskiaId),
                ItemKopurua = itemCount,
                EzabatutakoId = id
            };

            return Json(results);
        }

        // GET: Saskias/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var saskia = await _context.Saskia
                .FirstOrDefaultAsync(m => m.SaskiaId == id);
            if (saskia == null)
            {
                return NotFound();
            }

            return View(saskia);
        }

        // GET: Saskias/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Saskias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SaskiaId")] Saskia saskia)
        {
            if (ModelState.IsValid)
            {
                _context.Add(saskia);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(saskia);
        }

        // GET: Saskias/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var saskia = await _context.Saskia.FindAsync(id);
            if (saskia == null)
            {
                return NotFound();
            }
            return View(saskia);
        }

        // POST: Saskias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("SaskiaId")] Saskia saskia)
        {
            if (id != saskia.SaskiaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(saskia);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SaskiaExists(saskia.SaskiaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(saskia);
        }

        // GET: Saskias/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var saskia = await _context.Saskia
                .FirstOrDefaultAsync(m => m.SaskiaId == id);
            if (saskia == null)
            {
                return NotFound();
            }

            return View(saskia);
        }

        // POST: Saskias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var saskia = await _context.Saskia.FindAsync(id);
            _context.Saskia.Remove(saskia);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


private bool SaskiaExists(string id)
        {
            return _context.Saskia.Any(e => e.SaskiaId == id);
        }
    }
}

proiektua2/proiektua2/Views/Saskia/Index.cshtml
@using System.Globalization;
@model proiektua2.ViewModels.SaskiaViewModel

@{
    ViewData["Title"] = "Index";
}
<div class="container">
    <div id="update-massage"></div>
    <table class="table table-striped">
        <thead>
            <tr class="borgona">
                <th>Izena</th>
                <th>Describapena</th>
                <th>Irudia</th>

                <th>Kantitatea</th>

                <th>salneurria</th>
                <th>Descontua</th>
                <th>salneurria deskontuarekin</th>
                <th>Data</th>

            </tr>
        </thead>

        @foreach (var item in Model.SaskiaAleak)
        {
            <tr id="row-@item.Producto.id">
                <td>
                    @Html.DisplayFor(modelItem => item.Producto.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Producto.descripcion)
                </td>
                <td>
                    <img id="thumbnail" src="~/images/productos/@Html.DisplayFor(modelItem => item.Producto.imagen)" />
                </td>
                <td>
               
                    
                    
                    
                     <a asp-controller="Saskia" asp-action="SaskiaKendu" asp-route-id="@item.Producto.id" class="RemoveLink" data-id="@item.ProductoId">
                        <i class="fas fa-minus-circle borgona"></i>
                    </a>
                    <span id="item-count-@item.Producto.id">
                        @Html.DisplayFor(modelItem => item.Kantitatea)
                    </span>

                    <a  class="AddLink" data-id="@item.ProductoId">
                        <i class="fas fa-plus-circle borgona"></i>
                    </a>
                    @*<div class="col-md-2 padina col-height col-middle">
            <p class="row">
                <a href="" class="RemoveLink" data-id="@item.Id">
                    <span class="glyphicon glyphicon-minus"></span>
                </a>
                <span id="item-count-@item.Id">@item.Kantitatea</span>
                <a href="" class="AddLink" data-id="@item.Id">
                    <span class="glyphicon glyphicon-plus"></span>
                </a>
            </p>
        </div>*@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Producto.precio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Producto.Deskontua)
                </td>
                <td>

                    @{ float eskaintza = item.Producto.precio - (item.Producto.precio * item.Producto.Deskontua) / 100;}
                    @eskaintza
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data)
                </td>
            </tr>
       
        }

        <tr>
            <td><a class="btn btn-borgona text-light" asp-controller="Home" asp-action="Index">Bueltatu</a></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td class="float-right"><p>Guztira: <span id="cart-total">@Model.SaskiaGuztira.ToString("C2", CultureInfo.CurrentCulture)</span></p></td>
        </tr>
    </table>
    <div class="pull-left">
        <p class="button">
            <a class="btn btn-borgona" asp-area="" asp-controller="Home" asp-action="Index">Jarraitu erosten</a>
        </p>
    </div>

    <div class="pull-right">
        <p class="button">
            <a class="btn btn-borgona" asp-area="" asp-controller="Ordaindu" asp-action="Index">Ordaindu>></a>
        </p>
    </div>

</div>

@*
    ///////////////////////////
    <div class="container">
        <table class="table">
            <tbody>
                @foreach (var item in Model.SaskiaAleak)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Producto.Nombre)
                        </td>
                        <td>
                            <img src="~/images/productos/@Html.DisplayFor(modelItem => item.Producto.imagen)" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Kantitatea)
                        </td>
                        <td>
                            <!--<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>-->


                        </td>
                    </tr>
                }
            </tbody>
            <tr><td><p class="float-right">Guztira: @Model.SaskiaGuztira</p></td></tr>
        </table>
    </div>
*@