proiektua2/proiektua2/Controllers/MarcasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using proiektua2;
using proiektua2.Models;

namespace proiektua2.Controllers
{
    public class MarcasController : Controller
    {
        private readonly AdminDbContext _context;

        public MarcasController(AdminDbContext context)
        {
            _context = context;
        }

        // GET: Marcas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Marcas.ToListAsync());
        }

        // GET: Marcas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marca = await _context.Marcas
                .FirstOrDefaultAsync(m => m.id == id);
            if (marca == null)
            {
                return NotFound();
            }

            return View(marca);
        }

        // GET: Marcas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Marcas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Nombre")] Marca marca)
        {
            if (ModelState.IsValid)
            {
                _context.Add(marca);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(marca);
        }

        // GET: Marcas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marca = await _context.Marcas.FindAsync(id);
            if (marca == null)
            {
                return NotFound();
            }
            return View(marca);
        }

        // POST: Marcas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Nombre")] Marca marca)
        {
            if (id != marca.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(marca);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MarcaExists(marca.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(marca);
        }

        // GET: Marcas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marca = await _context.Marcas
                .FirstOrDefaultAsync(m => m.id == id);
            if (marca == null)
            {
                return NotFound();
            }

            return View(marca);
        }

        // POST: Marcas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var marca = await _context.Marcas.FindAsync(id);
            _context.Marcas.Remove(marca);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MarcaExists(int id)
        {
            return _context.Marcas.Any(e => e.id == id);
        }
    }
}

proiektua2/proiektua2/Controllers/SaskiasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using proiektua2;
using proiektua2.Models;
using proiektua2.Services;
using proiektua2.ViewModels;

namespace proiektua2.Controllers
{
    public class SaskiaController : Controller
    {
        private readonly AdminDbContext _context;
        private readonly ISaskiaService _saskiaService;
        private readonly IProductoService _ardoaService;
        public static Guid tempCartId ;
        public SaskiaController(AdminDbContext context,ISaskiaService saskiaService, IProductoService ardoaService)
        {
            _saskiaService = saskiaService;
            _ardoaService = ardoaService;
            _context = context;
        }

       /* public SaskiaController(AdminDbContext context)
        {
            _context = context;
        }*/

        // GET: Saskias
        public async Task<IActionResult> Index()
        {
            var cart = Saskia.SaskiaLortu();
            var saskiaViewModel = new SaskiaViewModel(); //ViewModel bat erabiliko dugu
            saskiaViewModel.SaskiaAleak = _saskiaService.SaskiaLortuAleak(cart.SaskiaId);
            saskiaViewModel.SaskiaGuztira = _saskiaService.Guztira(cart.SaskiaId);

            return View(saskiaViewModel);


            
        }
      
        public IActionResult SaskiaGehitu(int id)
        {
            var cart = Saskia.SaskiaLortu(); //aurretik sortu dugun Saskia klasea erabiliz
            _saskiaService.SaskiaGehitu(id, cart.SaskiaId); //zerbitzu berrian karritoan gehitzeko
            return RedirectToAction("Index");
        }
        public IActionResult SaskiaGehituJson(int id)
        {
            var cart = Saskia.SaskiaLortu();

            var saskiaItem = _saskiaService.SaskiaAleaDatuak(id, cart.SaskiaId);

            _saskiaService.SaskiaGehitu(id, cart.SaskiaId);

            var results = new SaskiaKenduViewModel
            {
                Mezua = HtmlEncoder.Default.Encode(saskiaItem.Producto.Nombre) + " zure saskira gehitu da",
                SaskiaGuztira = _saskiaService.Guztira(cart.SaskiaId),
                //ItemGuztiak = _saskiaService.ItemGuztiak(cart.SaskiaId),
                ItemKopurua = saskiaItem.Kantitatea,
                EzabatutakoId = id
            };

            return Json(results);
        }
        [HttpPost]
        public ActionResult SaskiaKendu(int id)
        {
            var cart = Saskia.SaskiaLortu();

            var saskiaItem = _saskiaService.SaskiaAleaDatuak(id, cart.SaskiaId);

            int itemCount = _saskiaService.SaskiaKendu(id, cart.SaskiaId);

            var results = new SaskiaKenduViewModel
            {
                Mezua = HtmlEncoder.Default.Encode(saskiaItem.Producto.Nombre) + " zure saskitik kendu da",
                SaskiaGuztira = _saskiaService.Guztira(cart.SaskiaId),
                ///ItemGuztiak = _saskiaService.ItemGuztiak(cart.SaskiaId),
                ItemKopurua = itemCount,
                EzabatutakoId = id
            };

            return Json(results);
        }

        // GET: Saskias/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var saskia = await _context.Saskia
                .FirstOrDefaultAsync(m => m.SaskiaId == id);
            if (saskia == null)
            {
                return NotFound();
            }

            return View(saskia);
        }

        // GET: Saskias/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Saskias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SaskiaId")] Saskia saskia)
        {
            if (ModelState.IsValid)
            {
                _context.Add(saskia);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(saskia);
        }

        // GET: Saskias/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var saskia = await _context.Saskia.FindAsync(id);
            if (saskia == null)
            {
                return NotFound();
            }
            return View(saskia);
        }

        // POST: Saskias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("SaskiaId")] Saskia saskia)
        {
            if (id != saskia.SaskiaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(saskia);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SaskiaExists(saskia.SaskiaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(saskia);
        }

        // GET: Saskias/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var saskia = await _context.Saskia
                .FirstOrDefaultAsync(m => m.SaskiaId == id);
            if (saskia == null)
            {
                return NotFound();
            }

            return View(saskia);
        }

        // POST: Saskias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var saskia = await _context.Saskia.FindAsync(id);
            _context.Saskia.Remove(saskia);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


private bool SaskiaExists(string id)
        {
            return _context.Saskia.Any(e => e.SaskiaId == id);
        }
    }
}

proiektua2/proiektua2/Views/Shared/_Disqus.cshtml
@model proiektua2.Models.Producto
<div id="disqus_thread"></div>
<script>
    (function () { // REQUIRED CONFIGURATION VARIABLE: EDIT THE SHORTNAME BELOW
        var d = document, s = d.createElement('script'); // IMPORTANT: Replace EXAMPLE with your forum shortname!
        s.src = 'https://pcgora-com.disqus.com/recommendations.js'; s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */

    var disqus_config = function () {
       /// this.page.url = '{{content.absolute_url}}';  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = @Model.id; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };

    (function () { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');

        s.src = 'https://pcgora-com.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>

<noscript>
    Please enable JavaScript to view the
    <a href="https://disqus.com/?ref_noscript" rel="nofollow">
        comments powered by Disqus.
    </a>
</noscript>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

    <div id="disqus_recommendations"></div>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-example">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Disqus Comment Apps</a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse-example">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">Home</a>
                    </li>
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <script src="~/scripts/jquery.js"></script>
    <script src="~/scripts/bootstrap.min.js"></script>
    <script id="dsq-count-scr" src="//pcgora-com.disqus.com/count.js" async></script>

proiektua2/proiektua2/Views/Shared/_Layout.cshtml
@using proiektua2.Controllers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - proiektua2</title>
    <script src="~/js/site.css"></script>
    <script src="~/js/jquery-3.6.0.slim.min.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/bootstrap-5.0.1-dist/css/bootstrap.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">proiektua2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @*<ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </li>
        </ul>*@

                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item dropdown">
               <div class="col-md-4 nireMenua">

        <div class="dropdown">
            <button class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                MARCAS
            </button>
            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
                HOLA
                @{var izena = "";
                    foreach (var item in Model)
                    {
                        if (item.Marca.Nombre != izena)
                        {
                            <li>
                                <a class="dropdown-item" href="#">
                                    @Html.DisplayFor(modelItem => item.Marca.Nombre)
                                    @{izena = item.Marca.Nombre;}
                                </a>
                            </li>
                        }
                    }
                }
            </ul>
        </div>&& AdminDbContext.sesion == true)
                </li>*@
                        @if (AdminDbContext.sesion == true)
                        {
                            ///////<i class="fa fa-shopping-cart"></i><a asp-area="" asp-controller="Saskia" asp-action="SaskiaGehitu" asp-route-id="@item.id">Karritora gehitu</a>
                            <li class="nav-item">
                                <a class="nav-link text-dark"> @AdminDbContext.user.usuario  </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Logout">Saioa amaitu</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="ErabiltzaileaErosketa">Erosketak</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Saskia" asp-action="Index">Karritora</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Ezarpenak">Ezarpenak</a>
                            </li>
                            @*<li class="nav-item">
                <div class="dropdown">
                    <button class="btn dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        ezarpenak
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenu2">

                        <button class="dropdown-item"><a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="ErabiltzaileaErosketa" asp-route-id="">Erosketak</a></button>
                        <button class="dropdown-item"><a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="pasahitzaAldatu" asp-route-id="">Pazaitza aldatu</a></button>


                    </div>
                </div>
            </li>*@
                            @if (AdminDbContext.user.tipo == "admin")
                            {


                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Erabiltzaileak</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Index">Produktuak</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="Index">Kategoriak</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Marcas" asp-action="Index">Markak</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Pedidos" asp-action="Index">Eskaerak</a>
                                </li>
                            }


                        }
                        else
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="registrar">Registrar</a>
                            </li>


                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - proiektua2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>